### ISSUE TITLE
Webmap ID is not recognized using files from Download.zip (master)

### ISSUE THREAD

**Issue by kenm09** [Esri/storymap-tour#21]
The index.html file used from map-tour-storytelling-template-js-master.zip is not honored when adding the webmap ID, a5019e8c55d547eab69c0777dcd7509a, which is the sample. Browsing to the index.html location under wwwroot throws error,  "An error has occurred 
Fatal error: Invalid configuration (web map or application identifier not specified in index.html)". The only way to use the webmap ID is to enter it in the URL such as: 
"http://mywebserver/MapTour/index.html?webmap=a5019e8c55d547eab69c0777dcd7509a". But the README.PDF states to enter the webmap ID  in the index.html file.

On the contrary, downloading Storytelling-MapTour-2.2.4.zip (User Download (source code not included)) works. Adding the webmap ID, a5019e8c55d547eab69c0777dcd7509a, is honored and shows the storymap.

**Comment by ccrozek** [comment]
In case it helps anyone else googling for this problem, I was having the same problem too (but with the map series template).  I found that if I lowercased the folder on the server that contained my app when navigating to it via URL, it worked and the "app id not specified" error went away.
