### ISSUE TITLE
Use intro point always true after build

### ISSUE THREAD

**Issue by phloem7** [Esri/storymap-tour#72]
Can change 'Use the first point as introduction' setting properly through builder (under 'Organize' button) running from 'src', but after grunt, running from 'deploy', value for 'Use the first point as introduction' reverts back to true immediately in builder.

Reproduce:
- load app builder from MapTour/src/index.html (e.g. http://localhost:8000/src/?appid=[APPID]&edit)
- change 'Use the first point as introduction' - works fine
- set up environment (npm install, npm install –g grunt-cli)
- add appid to index.html
- run grunt
- load app builder from MapTour/deploy/index.html (http://localhost:8000/deploy/index.html?edit)
- change 'Use the first point as introduction' - reverts to checked

**Comment by cooney** [comment]
This is by design.  That parameter can be overridden using the URL parameter 'firstRecordAsIntro'.  Or, you can alter the source code that overrides the configOptions in Core.js around line 122, and running grunt again.  
```
// Ignore index.html configuration on AGOL/Portal and development (except proxy/sharing URL)
    if( Helper.isArcGISHosted() || ! isProd() )
        configOptions = {
            proxyurl: configOptions.proxyurl,
            sharingurl: configOptions.sharingurl
        };
```
