### ISSUE TITLE
Allow Side Panel Layout and Cover Photo to Be Set Through Application Files

### ISSUE THREAD

**Issue by pmacMaps** [Esri/storymap-tour#78]
It appears that if you want to use the new "Side Panel" layout and optional cover photo, you _**must**_ use the web builder.

It would nice if options could be added into the **script** tag within the **index.html** file or the **maptour-config.js** file to enable these new features.

**Comment by cooney** [comment]
Hey Patrick,
These are actually already in place, but will only take effect in the production (deploy) version of your Map Tour.
