### ISSUE TITLE
Add support for JSON file containing tour points

### ISSUE THREAD

**Issue by pmacMaps** [Esri/storymap-tour#80]
It would be nice if in addition to a CSV file, you could use a JSON file as the source for the map tour points.

And please let me know if this should also go on the ideas site.

**Comment by cooney** [comment]
Hey Patrick,

While the Map Tour builder does not directly support JSON for tour points, you could start by creating a web map from JSON in the arcgis online web map viewer, then creating a Map Tour from that web map.  https://doc.arcgis.com/en/arcgis-online/reference/geojson.htm
